/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SankalpaSolutions.chamil.racebyrace.view;

import SankalpaSolutions.chamil.racebyrace.controller.CountryController;
import SankalpaSolutions.chamil.racebyrace.controller.PoraController;
import SankalpaSolutions.chamil.racebyrace.controller.RaceCardController;
import SankalpaSolutions.chamil.racebyrace.controller.ResultDetailsController;
import SankalpaSolutions.chamil.racebyrace.controller.ResultsController;
import SankalpaSolutions.chamil.racebyrace.model.Country;
import SankalpaSolutions.chamil.racebyrace.model.Pora;
import SankalpaSolutions.chamil.racebyrace.model.RaceCard;
import SankalpaSolutions.chamil.racebyrace.model.ResultDetails;
import SankalpaSolutions.chamil.racebyrace.model.Results;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win 8
 */
public class AddResults extends javax.swing.JPanel {

    private int counter;
    private int counterPora;
    private int maxValue;
    

    /**
     * Creates new form AddResults
     */
    public AddResults() {
        initComponents();

        try {

            jLabel10.setText("<html>Enter search Criteria &<br>Press enter to search.<br>Select the apropriate search<br>"
                    + "options and type the search text<br>bellow.<br>And the press enter key.<br>"
                    + " System will automaticly<br> list the maching items for you.</html>");
            jScrollPane6.setVisible(false);

            String[] cmbMenu = {"Win (1)", "Second (2)", "Third (3)", "Fourth (4)", "Fifth (5)"};
            jComboBox2.setModel(new DefaultComboBoxModel(cmbMenu));
        } catch (Exception ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1322, 540));
        setMinimumSize(new java.awt.Dimension(1322, 540));
        setPreferredSize(new java.awt.Dimension(1322, 540));

        jPanel1.setMaximumSize(new java.awt.Dimension(1322, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(1322, 540));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1322, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable9.setGridColor(new java.awt.Color(204, 204, 204));
        jTable9.getTableHeader().setReorderingAllowed(false);
        jTable9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable9MousePressed(evt);
            }
        });
        jTable9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable9KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(jTable9);
        if (jTable9.getColumnModel().getColumnCount() > 0) {
            jTable9.getColumnModel().getColumn(0).setMinWidth(50);
            jTable9.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 250, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SankalpaSolutions/chamil/racebyrace/images/1252769_small_checkboard copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, 140));

        jTextField1.setBackground(new java.awt.Color(255, 204, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 250, 25));

        jLabel2.setText("Country  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        jLabel3.setText("      Pora  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, 20));

        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, -1));

        jComboBox2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, -1));

        jLabel5.setText("       Horse Number  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 260, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setText("    Win side  :");

        jLabel9.setText("  Place side  :");

        jButton1.setText("Add");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jRadioButton2.setText("One 5th");
        jRadioButton2.setOpaque(false);

        jRadioButton3.setText("One 4th");
        jRadioButton3.setOpaque(false);

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Result", "Horse Name", "Win", "Place"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(60);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable2.getColumnModel().getColumn(2).setMinWidth(70);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(3).setMinWidth(70);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jButton4.setText("add NR");
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jTextField6.setBackground(new java.awt.Color(255, 204, 102));
        jTextField6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Select Horse  :");

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Non Runners (F1)  :");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(7, 7, 7)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 380, 260));

        jLabel8.setText("    Horse Name  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        jTextField4.setBackground(new java.awt.Color(255, 204, 102));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, -1));

        jLabel12.setText("      Place Of Event  :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 20));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pora", "Horse Name", "Win side", "Place Side", "2nd Place", "3rd Plce", "4th Place", "5th Place", "Non runners"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(70);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(1).setMinWidth(180);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(180);
            jTable1.getColumnModel().getColumn(8).setMinWidth(100);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 820, 300));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setText("Places");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 190, 410, 30));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 290, 120));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setText("Country");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 70, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setText("Win");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 190, 335, 30));

        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 840, 360));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Close");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, -30, 80, 30));

        jButton2.setText("Add (Ctrl)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 80, -1));

        jButton3.setText("Update");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 90, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Add Results")));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, 410));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SankalpaSolutions/chamil/racebyrace/images/centerBackground.jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable9MousePressed
        //int Row = jTable5.getSelectedRow();
        //    jTextField3.setText(jTable5.getValueAt(Row, 0).toString());
        //    jScrollPane5.setVisible(false);
        //    jTable5.setVisible(false);
    }//GEN-LAST:event_jTable9MousePressed

    private void jTable9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable9KeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                int Row = jTable9.getSelectedRow();
                jTextField1.setText(jTable9.getValueAt(Row, 1).toString());
                System.out.println("get Selected row eke value eka : " + jTable9.getValueAt(Row, 0).toString());
                jScrollPane6.setVisible(false);
                jTable9.setVisible(false);
                jTextField4.grabFocus();
                List<Pora> listPora = PoraController.searchAllPoraByIDNumber(Integer.parseInt(jTable9.getValueAt(Row,0).toString()));
                DefaultComboBoxModel cmb1 = (DefaultComboBoxModel) jComboBox1.getModel();
                System.out.println("country id eka : " + jTable9.getValueAt(Row, 1).toString());
                jComboBox1.removeAllItems();
                for (int i = 0; i < listPora.size(); i++) {

                    cmb1.addElement(listPora.get(i).getPora());
                    System.out.println("poraval : " + listPora.get(i).getPora());

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jTable9KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jTextField4.grabFocus();

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try {
            List<Country> list = CountryController.serchLikeCountryName(jTextField1.getText());
            int contryID = 0;
            for (int i = 0; i < list.size(); i++) {
                contryID = list.get(i).getCountry_ID();
                System.out.println("country id : " + contryID);
            }

//            DefaultComboBoxModel cmb1 = (DefaultComboBoxModel) jComboBox1.getModel();
//            ResultSet rs3 = Db.search("SELECT*FROM country_of_horse WHERE Pora='" + jTextField1.getText() + "'");
//            int contryID = 0;
//            while (rs3.next()) {
//                contryID = Integer.parseInt(rs3.getString("C_ID"));
//
//            }
//            List<Pora> listPora = PoraController.searchAllPoraByIDNumber(contryID);
//            DefaultComboBoxModel cmb1 = (DefaultComboBoxModel) jComboBox1.getModel();
//              System.out.println("country id eka : "+contryID);
//            jComboBox1.removeAllItems();
//            for (int i = 0; i < listPora.size(); i++) {
//              
//                cmb1.addElement(listPora.get(i).getPora());
//                System.out.println("poraval : " + listPora.get(i).getPora());
//                
//            }
//            ResultSet rs2 = Db.search("SELECT Pora FROM pora_of_horse WHERE C_ID='" + contryID + "'  ");
//            jComboBox1.removeAllItems();
//            while (rs2.next()) {
//                cmb1.addElement(rs2.getString("Pora"));
//            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        //   System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == 40) {
            jTable9.grabFocus();
            ListSelectionModel selectionModel = jTable9.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        System.gc();

        DefaultTableModel dtm3 = (DefaultTableModel) jTable9.getModel();
        if (jTextField1.getText().length() == 0) {
        } else {
            try {

                DefaultTableModel dtm = (DefaultTableModel) jTable9.getModel();
                List<Country> list = CountryController.serchLikeCountryName(jTextField1.getText());
                dtm.setRowCount(0);
                for (int i = 0; i < list.size(); i++) {
                    Vector v = new Vector();
                    v.add(list.get(i).getCountry_ID());
                    v.add(list.get(i).getCountry_Name());

                    dtm.addRow(v);
                    jScrollPane6.setVisible(true);
                    jTable9.setVisible(true);
                }

//                ResultSet rs1 = Db.search("SELECT Pora FROM country_of_horse WHERE Pora LIKE '" + jTextField1.getText() + "%'  ");
//                dtm.setRowCount(0);
//                while (rs1.next()) {
//                    Vector v = new Vector();
//                    v.add(rs1.getString("Pora"));
//
//                    System.out.println("" + rs1.getString("Pora"));
//                    dtm.addRow(v);
//                    //                    addHorse
//                    jScrollPane6.setVisible(true);
//                    jTable9.setVisible(true);
//                }
                if (dtm.getRowCount() == 0) {
                    jScrollPane6.setVisible(false);
                    jTable9.setVisible(false);
                } else {
                    jScrollPane6.setVisible(true);
                    jTable9.setVisible(true);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField3.grabFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jButton1.grabFocus();
        if (jTextField3.getText().length() == 0) {
            jButton1.setEnabled(false);
            jTextField3.grabFocus();
        } else {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        //          System.out.println("size : "+jComboBox1.get);
        if (jRadioButton1.isSelected()) {
           
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField4.grabFocus();
        } else {
            if (jLabel7.getText().equals("")) {

                jTextField4.grabFocus();
                jTextField4.setText("");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
                Vector v = new Vector();
                v.add(jComboBox2.getSelectedItem());
                v.add(jLabel7.getText());
                v.add(jTextField2.getText());
                v.add(jTextField3.getText());
                dtm.addRow(v);
                counter++;
                jTextField4.setText("");
                jLabel7.setText("");
                jTextField2.setText("");
                jTextField3.setText("");

                jComboBox2.setSelectedIndex(counter);
                if (jComboBox2.getSelectedIndex() != 0) {
                    jTextField2.setEditable(false);
                    System.out.println("txt eka flase");
                } else {
                    jTextField2.setEditable(true);
                }
                jTextField4.grabFocus();
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

        if (jRadioButton1.isSelected()) {
        }
        if (jComboBox2.getSelectedIndex() != 0) {
            jTextField2.setText("0");
            jTextField3.grabFocus();
        } else {
            jTextField2.grabFocus();
            jTextField2.setEditable(true);
        }
        if (jTextField4.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Plse enter horse 2");
            jTextField4.setText("0");
            jTextField4.grabFocus();
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost

        try {
            if (jRadioButton1.isSelected()) {
                if (jTextField4.getText().length() != 0) {
                    JOptionPane.showMessageDialog(null, "Plase unselect non-runners");
                    jRadioButton1.setSelected(false);
                    jTextField4.grabFocus();
                } else {
                    jTextField6.grabFocus();
                }
            } else {

                DefaultComboBoxModel cmb1 = (DefaultComboBoxModel) jComboBox1.getModel();

                List<RaceCard> list = RaceCardController.searchRaceCardByName(jComboBox1.getSelectedItem().toString());
                for (int i = 0; i < list.size(); i++) {
                    if (jTextField4.getText().equals(list.get(i).getRaceCard_PoraNumber())) {
                        jLabel7.setText(list.get(i).getRaceCard_HorseName());
                    }
                }

//                ResultSet rs3 = Db.search("SELECT Pora_ID,Horse_Name FROM race_card WHERE Pora='" + jComboBox1.getSelectedItem() + "'");
//                int contryID = 0;
//                while (rs3.next()) {
//                    if (jTextField4.getText().equals(rs3.getString("Pora_ID"))) {
//                        jLabel7.setText(rs3.getString("Horse_Name"));
//                    }
//                }
            }
        } catch (Exception ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

        if (evt.getKeyCode() == 112) {
            try {
                int Row = jTable9.getSelectedRow();
                jRadioButton1.setSelected(true);
                jTextField6.grabFocus();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        if (evt.getKeyCode() == 17) {
            jTextField4.setText("0");
            jButton2.grabFocus();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jTextField6.grabFocus();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            DefaultTableModel dtm2 = (DefaultTableModel) jTable2.getModel();
            int z = jTable1.getRowCount();
            int y = jTable2.getRowCount();
            String name = "0";
            String win = "0";
            String place = "0";
            String secplace = "0";
            String thirdplace = "0";
            String fourthplace = "0";
            String fifthplace = "0";
            counterPora++;

            maxValue = ResultsController.serchMaxItem();

//            ResultSet rs = Db.search("SELECT MAX(Result_Of_Pora_ID)FROM result_of_pora");
//            while (rs.next()) {
//                int max = rs.getInt("MAX(Result_Of_Pora_ID)");
//                max++;
//                maxValue = max;
//            }
            for (int i = 0; i < y; i++) {
                if (dtm2.getValueAt(i, 0).toString().equals("Win (1)")) {
                    name = (String) dtm2.getValueAt(i, 1);
                    win = (String) dtm2.getValueAt(i, 2);
                    place = (String) dtm2.getValueAt(i, 3);
                } else if (dtm2.getValueAt(i, 0).equals("Second (2)")) {
                    secplace = (String) dtm2.getValueAt(i, 3);
                } else if (dtm2.getValueAt(i, 0).equals("Third (3)")) {
                    thirdplace = (String) dtm2.getValueAt(i, 3);
                } else if (dtm2.getValueAt(i, 0).equals("Fourth (4)")) {
                    fourthplace = (String) dtm2.getValueAt(i, 3);
                } else if (dtm2.getValueAt(i, 0).equals("Fifth (5)")) {
                    fifthplace = (String) dtm2.getValueAt(i, 3);
                }
            }
            Results result = new Results(null, jComboBox1.getSelectedItem().toString());
            ResultsController.addResults(result);

//            Db.sud("INSERT into result_of_pora (Pora,Non_Runners) VALUES('" + jComboBox1.getSelectedItem() + "','" + jTextField5.getText() + "')");
            for (int i = 0; i < y; i++) {
                System.out.println("max val " + maxValue);
                ResultDetails resultdetails = new ResultDetails(null, maxValue, dtm2.getValueAt(i, 0).toString(), dtm2.getValueAt(i, 1).toString(), dtm2.getValueAt(i, 2).toString(), dtm2.getValueAt(i, 3).toString());
                ResultDetailsController.addResultDetails(resultdetails);
//                Db.sud("INSERT into result_of_pora_details VALUES('" + maxValue + "','" + dtm2.getValueAt(i, 0) + "','" + dtm2.getValueAt(i, 1) + "','" + dtm2.getValueAt(i, 2) + "','" + dtm2.getValueAt(i, 3) + "')");
            }

            v.add(jComboBox1.getSelectedItem());
            dtm.addRow(v);
            dtm.setValueAt(name, z, 1);
            dtm.setValueAt(win, z, 2);
            dtm.setValueAt(place, z, 3);
            dtm.setValueAt(secplace, z, 4);
            dtm.setValueAt(thirdplace, z, 5);
            dtm.setValueAt(fourthplace, z, 6);
            dtm.setValueAt(fifthplace, z, 7);
            
            jTextField4.grabFocus();
            jRadioButton1.setSelected(false);
            dtm2.setRowCount(0);
           
            jTextField3.setText("");
            counter = 0;

            jComboBox1.setSelectedIndex(counterPora);
            jComboBox2.setSelectedIndex(counter);
        } catch (Exception ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        jButton4.grabFocus();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        try {
            List<RaceCard> list = RaceCardController.searchRaceCardByName(jComboBox1.getSelectedItem().toString());
            for (int i = 0; i < list.size(); i++) {

                if (jTextField6.getText().equals(list.get(i).getRaceCard_PoraNumber())) {
                    jLabel16.setText(list.get(i).getRaceCard_HorseName());
                }
            }

//            ResultSet rs3 = Db.search("SELECT Pora_ID,Horse_Name FROM race_card WHERE Pora='" + jComboBox1.getSelectedItem() + "'");
//            int contryID = 0;
//            while (rs3.next()) {
//                if (jTextField6.getText().equals(rs3.getString("Pora_ID"))) {
//                    jLabel16.setText(rs3.getString("Horse_Name"));
//                }
//            }
            if (jTextField6.getText().length() == 0) {
                //                JOptionPane.showMessageDialog(rootPane, "Plse enter horse");
                //                jTextField6.grabFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(AddResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        if (evt.getKeyCode() == 17) {
            jTextField4.setText("0");
            jButton2.grabFocus();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
       DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel();
        
        if (jTextField6.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Plse enter horse 1");
        } else {
            Vector v=new Vector();
            v.add("Non Runner");
            v.add(jLabel16.getText());
            v.add("10");
            v.add("10");
            dtm.addRow(v);
//            if (jTextField5.getText().equals("")) {
//
//                jTextField5.setText(jTextField6.getText());
//            } else {
//                jTextField5.setText(jTextField5.getText() + "," + jTextField6.getText());
//            }
        }
        jLabel16.setText("");
        jTextField6.setText("");
        jTextField6.grabFocus();
    }//GEN-LAST:event_jButton4KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
